---
- interface: examples.framework.integrations.common.ISession
  constructor: examples.framework.integrations.redis.RedisSession

- interface: examples.framework.integrations.common.IDao
  qualifier: examples.users.entities.User
  constructor: examples.framework.integrations.django.DjangoDao
